### ISSUE TITLE
Elements who loads after user-interaction, improve user-interation simulation

### ISSUE THREAD

**Issue by pedddro** [ceckoslab/inp-measure-puppeteer#2]
I'm trying to make it work by adding a scroll with:

```
// scroll to simulate interaction
async function autoScroll(page){
  await page.evaluate(async () => {
      await new Promise((resolve) => {
          var totalHeight = 0;
          var distance = 10;
          var timer = setInterval(() => {
              var scrollHeight = document.body.scrollHeight;
              window.scrollBy(0, distance);
              totalHeight += distance;

              if(totalHeight >= scrollHeight - window.innerHeight){
                  clearInterval(timer);
                  resolve();
              }
          }, 100);
      });
  });
};
```
Im running it before the element appear:
```
  // Simulate user-interaction
  await autoScroll(page);

  // Wait for the element to be present in the DOM
  await page.waitForSelector(elementToInteractWith);
```
but couldn't get it working, maybe opening a issue here will help.

**Comment by ceckoslab** [comment]
Hello Peddro, I created an example that worked for me. Please check this Pull Request and cherry pick whatever you need: https://github.com/ceckoslab/inp-measure-puppeteer/pull/3

Is it possible that you missed to change this part `### ADD THE CSS SELECTOR HERE ###` in index.js ?

**Comment by pedddro** [comment]
Thanks @ceckoslab. I managed to get it to work. 

In Wordpress, most sites use delay after user interaction for scripts to improve Pagespeed, and the script without interaction skews the results.

I can add a PR to amend it, let me know your thoughts.

**Comment by ceckoslab** [comment]
Thank you @pedddro ,

A PR will be appreciated! I am interested to see the code change :)
